name: Run
on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    name: "Run"
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK 11.0.11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.11
      - name: Run
        env:
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_TO_EMAIL: ${{ secrets.SMTP_TO_EMAIL }}
          SMTP_FROM_EMAIL: ${{ secrets.SMTP_FROM_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: ./gradlew clean run
